apiVersion: v1
kind: Service
metadata:
  name: gdscfptu-user-service-service
spec:
  type: LoadBalancer
  ports:
    - name: user-service
      protocol: TCP
      port: 3000
      targetPort: api-port
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis-port
  selector:
    app: user-service-depl
